
const countries = [
  { "src": "/img/countries/albania.png", country: "albania", capital: "tirana", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/afghanistan.png", country: "afghanistan", capital: "kabul", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/algeria.png", country: "algeria", capital: "algiers", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/armenia.png", country: "armenia", capital: "yerevan", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/australia.png", country: "australia", capital: "canberra", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/austria.png", country: "austria", capital: "vienna", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/azerbaijan.png", country: "azerbaijan", capital: "baku", poplulation: "38.9million", isCountry: true, matched: false },
  { "src": "/img/countries/bahamas.png", country: "bahamas", capital: "Nassau", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/bahrain.png", country: "bahrain", capital: "manama", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/bangladesh.png", country: "bangladesh", capital: "dhaka", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/barbados.png", country: "barbados", capital: "bridgetown", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/belarus.png", country: "belarus", capital: "minsk", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/belgium.png", country: "belgium", capital: "brussels", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/belize.png", country: "belize", capital: "Belmopan", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/bhutan.png", country: "bhutan", capital: "Thimphu", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/bolivia.png", country: "bolivia", capital: "sucre", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/botswana.png", country: "botswana", capital: "Gaborone", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/brazil.png", country: "brazil", capital: "brasilia", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/bulgaria.png", country: "bulgaria", capital: "sofia", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/burkinafaso.png", country: "burkina Faso", capital: "Ouagadougou", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/burundi.png", country: "burundi", capital: "gitega", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/caboverde.png", country: "Cabo Verde", capital: "Praia", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/cambodia.png", country: "cambodia", capital: "Phnom Penh", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/cameroon.png", country: "cameroon", capital: "Yaoundé", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/canada.png", country: "canada", capital: "Ottawa", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/chad.png", country: "chad", capital: "N'Djamena", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/chile.png", country: "chile", capital: "Santiago", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/china.png", country: "china", capital: "Beijing", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/colombia.png", country: "colombia", capital: "Bogotá", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/comoros.png", country: "comoros", capital: "Moroni", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/costarica.png", country: "costarica", capital: "San José", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/croatia.png", country: "croatia", capital: "Zagreb", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/cuba.png", country: "cuba", capital: "Havana", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/finland.png", country: "finland", capital: "Helsinki", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/france.png", country: "france", capital: "Paris", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/greece.png", country: "greece", capital: "Athens", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/germany.png", country: "germany", capital: "Berlin", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/hungary.png", country: "hungary", capital: "Budapest", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/iceland.png", country: "iceland", capital: "Reykjavík", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/indonesia.png", country: "indonesia", capital: "Jakarta", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/ireland.png", country: "ireland", capital: "Dublin", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/italy.png", country: "italy", capital: "Rome", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/ivorycoast.png", country: "Côte d'Ivoire", capital: "Yamoussoukro", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/jamaica.png", country: "jamaica", capital: "Kingston", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/japan.png", country: "japan", capital: "Tokyo", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/monaco.png", country: "monaco", capital: "Monaco", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/portugal.png", country: "portugal", capital: "Lisbon", poplulation: "", isCountry: true, matched: false },
  { "src": "/img/countries/spain.png", country: "spain", capital: "Madrid", poplulation: "", isCountry: true, matched: false },
]

const capitals = [
  { "src": "/img/countries/afghanistan.png", country: "afghanistan", capital: "kabul", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/albania.png", country: "albania", capital: "tirana", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/algeria.png", country: "algeria", capital: "algiers", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/armenia.png", country: "armenia", capital: "yerevan", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/australia.png", country: "australia", capital: "canberra", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/austria.png", country: "austria", capital: "Vienna", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/azerbaijan.png", country: "azerbaijan", capital: "baku", poplulation: "38.9million", isCountry: false, matched: false },
  { "src": "/img/countries/bahamas.png", country: "bahamas", capital: "Nassau", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/bahrain.png", country: "bahrain", capital: "manama", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/bangladesh.png", country: "bangladesh", capital: "dhaka", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/barbados.png", country: "barbados", capital: "bridgetown", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/belarus.png", country: "belarus", capital: "minsk", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/belgium.png", country: "belgium", capital: "brussels", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/belize.png", country: "belize", capital: "Belmopan", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/bhutan.png", country: "bhutan", capital: "Thimphu", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/bolivia.png", country: "bolivia", capital: "sucre", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/botswana.png", country: "botswana", capital: "Gaborone", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/brazil.png", country: "brazil", capital: "brasilia", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/bulgaria.png", country: "bulgaria", capital: "sofia", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/burkinafaso.png", country: "burkina Faso", capital: "Ouagadougou", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/burundi.png", country: "burundi", capital: "gitega", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/caboverde.png", country: "Cabo Verde", capital: "Praia", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/cambodia.png", country: "cambodia", capital: "Phnom Penh", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/cameroon.png", country: "cameroon", capital: "Yaoundé", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/canada.png", country: "canada", capital: "Ottawa", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/chad.png", country: "chad", capital: "N'Djamena", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/chile.png", country: "chile", capital: "Santiago", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/china.png", country: "china", capital: "Beijing", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/colombia.png", country: "colombia", capital: "Bogotá", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/comoros.png", country: "comoros", capital: "Moroni", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/costarica.png", country: "costarica", capital: "San José", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/croatia.png", country: "croatia", capital: "Zagreb", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/cuba.png", country: "cuba", capital: "Havana", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/finland.png", country: "finland", capital: "Helsinki", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/france.png", country: "france", capital: "Paris", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/greece.png", country: "greece", capital: "Athens", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/germany.png", country: "germany", capital: "Berlin", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/hungary.png", country: "hungary", capital: "Budapest", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/iceland.png", country: "iceland", capital: "Reykjavík", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/indonesia.png", country: "indonesia", capital: "Jakarta", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/ireland.png", country: "ireland", capital: "Dublin", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/italy.png", country: "italy", capital: "Rome", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/ivorycoast.png", country: "Côte d'Ivoire", capital: "Yamoussoukro", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/jamaica.png", country: "jamaica", capital: "Kingston", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/japan.png", country: "japan", capital: "Tokyo", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/monaco.png", country: "monaco", capital: "Monaco", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/portugal.png", country: "portugal", capital: "Lisbon", poplulation: "", isCountry: false, matched: false },
  { "src": "/img/countries/spain.png", country: "spain", capital: "Madrid", poplulation: "", isCountry: false, matched: false },
]

export { countries, capitals }